export const PORTS = {
  newark: {
    name: 'Port Newark',
    fullName: 'Port of New York and New Jersey',
    city: 'Newark', state: 'NJ', zip: '07114',
    address: 'Port Newark-Elizabeth Marine Terminal, 241 Calcutta St, Newark, NJ 07114',
    gateHours: 'Mon-Fri 7AM-4PM. Appointment required for delivery. Allow extra time during peak season as scheduling slots fill quickly.',
    storageInfo: 'Free period varies by shipping line, typically 4-5 days. Demurrage charges apply after free time expires and vary by carrier. Contact your ocean freight provider for exact rates.',
    tips: 'Limited parking for car carriers — carriers must schedule delivery windows in advance. High volume port, so expect occasional delays during peak shipping months. Nearest Copart yards: Englishtown NJ, Hillsborough NJ.',
    description: 'The largest port on the East Coast for vehicle exports. Port Newark-Elizabeth Marine Terminal handles RoRo and container shipments to Europe, Africa, and the Middle East. The terminal processes thousands of vehicles monthly, making it the primary gateway for exporters in the Northeastern US. Due to its high volume, coordination with terminal operators is critical to avoid delays and storage fees. Y7 Logistics has established relationships with terminal staff to ensure smooth vehicle intake.',
    metaTitle: 'Auto Transport to Port Newark, NJ',
    metaDesc: 'Vehicle shipping to Port Newark-Elizabeth Marine Terminal. Door-to-port auto transport for export. Licensed broker, verified carriers.',
    routes: [
      { from: 'Miami, FL', days: '2-3' },
      { from: 'Chicago, IL', days: '2-3' },
      { from: 'Houston, TX', days: '3-4' },
      { from: 'Los Angeles, CA', days: '5-7' },
      { from: 'Atlanta, GA', days: '2-3' },
    ],
    documents: ['Vehicle title or export documentation', 'Gate pass (if from auction)', 'Port delivery order', 'EPA/DOT compliance forms (for imports)'],
    destinations: 'Europe, West Africa, Middle East, South America',
  },
  houston: {
    name: 'Port of Houston',
    fullName: 'Port of Houston, Barbours Cut & Bayport Terminals',
    city: 'Houston', state: 'TX', zip: '77029',
    address: 'Barbours Cut Terminal, 1000 Barbours Cut Blvd, La Marque, TX 77568',
    gateHours: 'Mon-Fri 7AM-5PM. Saturday by appointment only. Gate appointments are recommended to avoid extended wait times.',
    storageInfo: 'Warehouse rates vary by terminal operator, typically $5-15/day after the free storage period ends. Container storage rates differ from RoRo — confirm with your freight forwarder.',
    tips: 'Texas has a massive Copart/IAA presence — many auction-to-port moves originate here. Hot weather during summer months can affect scheduling and driver availability. Nearest Copart yards: Houston South, Houston, Dallas.',
    description: 'The top US port for vehicle exports by volume. Handles RoRo and container shipments to Africa, the Middle East, Central and South America. Barbours Cut and Bayport terminals together process more vehicle exports than any other US port, with direct ocean service to over 200 global destinations. The port offers both RoRo and container loading options, giving exporters flexibility based on destination requirements. Its central Gulf Coast location makes it ideal for vehicles originating from Texas, the Midwest, and the Southern US.',
    metaTitle: 'Auto Transport to Port of Houston, TX',
    metaDesc: 'Vehicle shipping to Port of Houston. Largest US vehicle export port. Door-to-port auto transport with verified carriers.',
    routes: [
      { from: 'Dallas, TX', days: '1' },
      { from: 'Miami, FL', days: '2-3' },
      { from: 'Chicago, IL', days: '2-3' },
      { from: 'New York, NY', days: '3-4' },
      { from: 'Los Angeles, CA', days: '3-4' },
    ],
    documents: ['Vehicle title or bill of sale', 'Gate pass (if from auction)', 'Export documentation', 'Customs/broker release forms'],
    destinations: 'West Africa, Middle East, Central America, South America',
  },
  savannah: {
    name: 'Port of Savannah',
    fullName: 'Georgia Ports Authority \u2014 Garden City Terminal',
    city: 'Savannah', state: 'GA', zip: '31402',
    address: 'Garden City Terminal, 2 Main St, Garden City, GA 31408',
    gateHours: 'Mon-Fri 8AM-4:30PM. No weekend gate hours for vehicle deliveries. Plan arrivals early in the day for best turnaround.',
    storageInfo: 'Container freight station rates apply. Storage fees are generally lower than Newark or Houston. Contact Georgia Ports Authority for current rate schedules.',
    tips: 'Growing port with competitive ocean freight rates to Europe and Africa. Significantly less congestion than Newark or Houston, making it a smart choice for exporters seeking faster turnaround. Good for European exports with direct RoRo service.',
    description: 'Major Southeast port with competitive rates for European and African destinations. Fast-growing vehicle export hub. Garden City Terminal is one of the fastest-growing container terminals in the US, and its vehicle handling capabilities have expanded significantly in recent years. The port offers competitive ocean freight rates, particularly for European destinations, and its lower congestion levels translate to faster processing times. Its Southeast location provides efficient access from Florida, the Carolinas, and the broader Southern US.',
    metaTitle: 'Auto Transport to Port of Savannah, GA',
    metaDesc: 'Vehicle shipping to Port of Savannah. Southeast hub for auto export. Competitive rates to Europe and Africa.',
    routes: [
      { from: 'Atlanta, GA', days: '1' },
      { from: 'Miami, FL', days: '1-2' },
      { from: 'Charlotte, NC', days: '1-2' },
      { from: 'New York, NY', days: '2-3' },
      { from: 'Chicago, IL', days: '2-3' },
    ],
    documents: ['Vehicle title', 'Gate pass (if from auction)', 'Port receiving instructions', 'Export documentation'],
    destinations: 'Europe, West Africa, East Africa',
  },
  'los-angeles': {
    name: 'Port of Los Angeles',
    fullName: 'Port of Los Angeles \u2014 WorldCargo Terminal',
    city: 'Los Angeles', state: 'CA', zip: '90731',
    address: 'WorldCargo Terminal, 300 E Ocean Blvd, Long Beach, CA 90802',
    gateHours: 'Mon-Fri 7AM-5PM. Appointment required for all vehicle deliveries. Same-day gate appointments are rarely available during peak periods.',
    storageInfo: 'Terminal storage ranges from $10-25/day after the free period expires. Free time is typically 3-4 days depending on the shipping line. Warehouse staging near the port is recommended for bulk shipments.',
    tips: 'Strict CARB (California Air Resources Board) compliance requirements for carriers entering the port area — older trucks may be denied entry. Extended wait times are common, especially during peak container season. Use warehouses near the port for staging vehicles before terminal delivery.',
    description: 'Pacific gateway for vehicle shipments to Asia, Australia, and Oceania. Largest container port in the Western Hemisphere. The Port of Los Angeles and adjacent Port of Long Beach together form the busiest port complex in the Americas, handling a significant volume of vehicle exports to Pacific Rim destinations. Carriers delivering vehicles to this port must comply with California Air Resources Board (CARB) emissions requirements, which restricts older diesel trucks from entering the port area. Planning and advance scheduling are essential due to the high volume of container traffic.',
    metaTitle: 'Auto Transport to Port of Los Angeles, CA',
    metaDesc: 'Vehicle shipping to Port of Los Angeles. Pacific gateway for auto export to Asia, Australia. Door-to-port transport.',
    routes: [
      { from: 'Phoenix, AZ', days: '1' },
      { from: 'Las Vegas, NV', days: '1' },
      { from: 'San Francisco, CA', days: '1' },
      { from: 'Dallas, TX', days: '2-3' },
      { from: 'New York, NY', days: '5-7' },
    ],
    documents: ['Vehicle title', 'Bill of sale', 'Customs documentation', 'EPA/DOT compliance (imports)'],
    destinations: 'Asia, Australia, New Zealand, Pacific Islands',
  },
  baltimore: {
    name: 'Port of Baltimore',
    fullName: 'Dundalk Marine Terminal',
    city: 'Baltimore', state: 'MD', zip: '21224',
    address: 'Dundalk Marine Terminal, 2700 Broening Hwy, Baltimore, MD 21224',
    gateHours: 'Mon-Fri 7AM-4PM. No weekend gate access for standard vehicle deliveries. Terminal appointments recommended but not always required.',
    storageInfo: 'Storage rates vary by terminal operator. Dundalk Marine Terminal offers competitive rates for RoRo staging. Contact the terminal directly for current fee schedules.',
    tips: 'Premier RoRo port — excellent for European destinations with frequent direct sailings. Less congestion than Newark, making it a preferred alternative for Mid-Atlantic exporters. Close proximity to DC/VA auction yards including Copart and IAA locations in Virginia and Maryland.',
    description: 'Premier East Coast RoRo terminal for vehicles heading to Europe. Dundalk Marine Terminal is one of the top vehicle-handling ports in the US. Baltimore has long been recognized as a leading RoRo port, with purpose-built facilities for efficient vehicle processing and loading. The port handles both import and export vehicle traffic, with particularly strong service to European and Mediterranean destinations. Its strategic Mid-Atlantic location provides easy access from the Washington DC metro area, Virginia, and Pennsylvania, and its lower congestion compared to Newark makes it an increasingly popular choice for exporters.',
    metaTitle: 'Auto Transport to Port of Baltimore, MD',
    metaDesc: 'Vehicle shipping to Port of Baltimore Dundalk Terminal. Top RoRo port for European vehicle export. Licensed broker.',
    routes: [
      { from: 'Washington, DC', days: '1' },
      { from: 'Philadelphia, PA', days: '1' },
      { from: 'New York, NY', days: '1-2' },
      { from: 'Charlotte, NC', days: '1-2' },
      { from: 'Chicago, IL', days: '2-3' },
    ],
    documents: ['Vehicle title', 'Gate pass (if from auction)', 'Port delivery order', 'Export documentation'],
    destinations: 'Europe, Mediterranean, Middle East',
  },
  jacksonville: {
    name: 'Port of Jacksonville',
    fullName: 'JAXPORT \u2014 Blount Island Marine Terminal',
    city: 'Jacksonville', state: 'FL', zip: '32206',
    address: 'Blount Island Marine Terminal, 9620 Dave Rawls Blvd, Jacksonville, FL 32226',
    gateHours: 'Mon-Fri 8AM-4:30PM. No weekend gate access for vehicle deliveries. Early morning arrivals recommended for fastest processing.',
    storageInfo: 'JAXPORT standard storage rates apply. Rates are competitive compared to larger ports. Contact JAXPORT terminal operations for current fee schedules and free time allowances.',
    tips: 'Best port for Caribbean and Central America shipments with frequent direct sailings. Florida has extremely high auction volume — many Copart and IAA yards are located nearby, making auction-to-port moves fast and affordable. Quick turnaround times compared to busier ports.',
    description: 'Gateway to the Caribbean and South America. Specializes in RoRo shipments for vehicles heading to Central America and the islands. JAXPORT Blount Island Marine Terminal is one of the top vehicle-handling ports in the Southeastern US, with direct ocean service to the Caribbean, Central America, and South America. The port benefits from Florida\'s massive used vehicle market and proximity to numerous Copart and IAA auction locations, making it the go-to port for exporters buying at auction and shipping to Caribbean and Latin American destinations. Turnaround times are generally faster than at larger ports like Houston or Newark.',
    metaTitle: 'Auto Transport to Port of Jacksonville, FL',
    metaDesc: 'Vehicle shipping to JAXPORT Jacksonville. Caribbean and South America gateway. Door-to-port auto transport.',
    routes: [
      { from: 'Miami, FL', days: '1' },
      { from: 'Orlando, FL', days: '1' },
      { from: 'Atlanta, GA', days: '1-2' },
      { from: 'New York, NY', days: '2-3' },
      { from: 'Houston, TX', days: '2-3' },
    ],
    documents: ['Vehicle title or bill of sale', 'Gate pass (if from auction)', 'JAXPORT delivery instructions', 'Export documentation'],
    destinations: 'Caribbean, Central America, South America',
  },
};
