export const PORTS = {
  newark: {
    name: 'Port Newark',
    fullName: 'Port of New York and New Jersey',
    city: 'Newark', state: 'NJ', zip: '07114',
    description: 'The largest port on the East Coast for vehicle exports. Port Newark-Elizabeth Marine Terminal handles RoRo and container shipments to Europe, Africa, and the Middle East.',
    metaTitle: 'Auto Transport to Port Newark, NJ',
    metaDesc: 'Vehicle shipping to Port Newark-Elizabeth Marine Terminal. Door-to-port auto transport for export. Licensed broker, verified carriers.',
    routes: [
      { from: 'Miami, FL', days: '2-3' },
      { from: 'Chicago, IL', days: '2-3' },
      { from: 'Houston, TX', days: '3-4' },
      { from: 'Los Angeles, CA', days: '5-7' },
      { from: 'Atlanta, GA', days: '2-3' },
    ],
    documents: ['Vehicle title or export documentation', 'Gate pass (if from auction)', 'Port delivery order', 'EPA/DOT compliance forms (for imports)'],
    destinations: 'Europe, West Africa, Middle East, South America',
  },
  houston: {
    name: 'Port of Houston',
    fullName: 'Port of Houston, Barbours Cut & Bayport Terminals',
    city: 'Houston', state: 'TX', zip: '77029',
    description: 'The top US port for vehicle exports by volume. Handles RoRo and container shipments to Africa, the Middle East, Central and South America.',
    metaTitle: 'Auto Transport to Port of Houston, TX',
    metaDesc: 'Vehicle shipping to Port of Houston. Largest US vehicle export port. Door-to-port auto transport with verified carriers.',
    routes: [
      { from: 'Dallas, TX', days: '1' },
      { from: 'Miami, FL', days: '2-3' },
      { from: 'Chicago, IL', days: '2-3' },
      { from: 'New York, NY', days: '3-4' },
      { from: 'Los Angeles, CA', days: '3-4' },
    ],
    documents: ['Vehicle title or bill of sale', 'Gate pass (if from auction)', 'Export documentation', 'Customs/broker release forms'],
    destinations: 'West Africa, Middle East, Central America, South America',
  },
  savannah: {
    name: 'Port of Savannah',
    fullName: 'Georgia Ports Authority \u2014 Garden City Terminal',
    city: 'Savannah', state: 'GA', zip: '31402',
    description: 'Major Southeast port with competitive rates for European and African destinations. Fast-growing vehicle export hub.',
    metaTitle: 'Auto Transport to Port of Savannah, GA',
    metaDesc: 'Vehicle shipping to Port of Savannah. Southeast hub for auto export. Competitive rates to Europe and Africa.',
    routes: [
      { from: 'Atlanta, GA', days: '1' },
      { from: 'Miami, FL', days: '1-2' },
      { from: 'Charlotte, NC', days: '1-2' },
      { from: 'New York, NY', days: '2-3' },
      { from: 'Chicago, IL', days: '2-3' },
    ],
    documents: ['Vehicle title', 'Gate pass (if from auction)', 'Port receiving instructions', 'Export documentation'],
    destinations: 'Europe, West Africa, East Africa',
  },
  'los-angeles': {
    name: 'Port of Los Angeles',
    fullName: 'Port of Los Angeles \u2014 WorldCargo Terminal',
    city: 'Los Angeles', state: 'CA', zip: '90731',
    description: 'Pacific gateway for vehicle shipments to Asia, Australia, and Oceania. Largest container port in the Western Hemisphere.',
    metaTitle: 'Auto Transport to Port of Los Angeles, CA',
    metaDesc: 'Vehicle shipping to Port of Los Angeles. Pacific gateway for auto export to Asia, Australia. Door-to-port transport.',
    routes: [
      { from: 'Phoenix, AZ', days: '1' },
      { from: 'Las Vegas, NV', days: '1' },
      { from: 'San Francisco, CA', days: '1' },
      { from: 'Dallas, TX', days: '2-3' },
      { from: 'New York, NY', days: '5-7' },
    ],
    documents: ['Vehicle title', 'Bill of sale', 'Customs documentation', 'EPA/DOT compliance (imports)'],
    destinations: 'Asia, Australia, New Zealand, Pacific Islands',
  },
  baltimore: {
    name: 'Port of Baltimore',
    fullName: 'Dundalk Marine Terminal',
    city: 'Baltimore', state: 'MD', zip: '21224',
    description: 'Premier East Coast RoRo terminal for vehicles heading to Europe. Dundalk Marine Terminal is one of the top vehicle-handling ports in the US.',
    metaTitle: 'Auto Transport to Port of Baltimore, MD',
    metaDesc: 'Vehicle shipping to Port of Baltimore Dundalk Terminal. Top RoRo port for European vehicle export. Licensed broker.',
    routes: [
      { from: 'Washington, DC', days: '1' },
      { from: 'Philadelphia, PA', days: '1' },
      { from: 'New York, NY', days: '1-2' },
      { from: 'Charlotte, NC', days: '1-2' },
      { from: 'Chicago, IL', days: '2-3' },
    ],
    documents: ['Vehicle title', 'Gate pass (if from auction)', 'Port delivery order', 'Export documentation'],
    destinations: 'Europe, Mediterranean, Middle East',
  },
  jacksonville: {
    name: 'Port of Jacksonville',
    fullName: 'JAXPORT \u2014 Blount Island Marine Terminal',
    city: 'Jacksonville', state: 'FL', zip: '32206',
    description: 'Gateway to the Caribbean and South America. Specializes in RoRo shipments for vehicles heading to Central America and the islands.',
    metaTitle: 'Auto Transport to Port of Jacksonville, FL',
    metaDesc: 'Vehicle shipping to JAXPORT Jacksonville. Caribbean and South America gateway. Door-to-port auto transport.',
    routes: [
      { from: 'Miami, FL', days: '1' },
      { from: 'Orlando, FL', days: '1' },
      { from: 'Atlanta, GA', days: '1-2' },
      { from: 'New York, NY', days: '2-3' },
      { from: 'Houston, TX', days: '2-3' },
    ],
    documents: ['Vehicle title or bill of sale', 'Gate pass (if from auction)', 'JAXPORT delivery instructions', 'Export documentation'],
    destinations: 'Caribbean, Central America, South America',
  },
};
