import { Link } from 'react-router-dom';
import PageMeta from '../../../components/PageMeta';
import BreadcrumbSchema from '../../../components/BreadcrumbSchema';
import styles from './GuidePage.module.css';

// DESIGN-V2-W5-T06: V2 "Dispatch Board" restyle. All heading texts/levels/
// order, copy, and table values (verified Copart fee figures: gate $95/$65,
// env $15, late $50, 3-biz-day) are byte-identical to V1; shells + tokens only.

export default function CopartGatePassGuide() {
  return (
    <div className={styles.page}>
      <PageMeta
        title="Copart Gate Pass Guide — How It Works, Common Failures, Yard Cutoffs"
        description="Technical guide to Copart gate passes. Generation timing, payment clearance, Transporter App requirements, common failure modes, and yard cutoff times that control pickup."
        path="/copart-gate-pass-guide"
      />
      <BreadcrumbSchema items={[
        { name: 'Home', url: '/' },
        { name: 'Copart Shipping', url: '/copart-shipping' },
        { name: 'Gate Pass Guide', url: '/copart-gate-pass-guide' },
      ]} />

      {/* Hero — board band */}
      <section className={styles.hero}>
        <div className={styles.heroInner}>
          <nav aria-label="Breadcrumb" className={styles.breadcrumb}>
            <Link to="/" className={styles.crumbLink}>Home</Link>
            <span className={styles.crumbSep}>/</span>
            <Link to="/copart-shipping" className={styles.crumbLink}>Copart Shipping</Link>
            <span className={styles.crumbSep}>/</span>
            <span className={styles.crumbCurrent}>Gate Pass Guide</span>
          </nav>

          <span className={styles.kicker}>Yard process guide</span>

          <h1 className={styles.h1}>
            The Copart Gate Pass: How It Works, Why It Fails, and Why Yard Cutoffs Control Pickup
          </h1>
        </div>
      </section>

      <div className={styles.body}>
        <p className={styles.intro}>
          This is the technical process documentation. If a carrier gets turned away at a Copart
          yard, one of the items below is almost always the reason. Understanding the mechanics
          saves dispatches, saves storage days, and saves the &quot;why is my car still sitting at
          the yard&quot; phone call.
        </p>

        <h2 className={styles.h2}>What a Copart gate pass actually is</h2>
        <p className={styles.p}>
          A gate pass is a digital release authorization generated by Copart once your payment has
          cleared and the account is in good standing. It ties together: buyer number, lot number,
          vehicle identifier, and a gate pass PIN. Without it, yard security turns carriers back —
          no exceptions, no arguing, no supervisor override.
        </p>

        <h2 className={styles.h2}>How much is the Copart gate fee in 2026?</h2>
        <p className={styles.p}>
          The Copart gate fee is <strong>$95 per vehicle</strong> for standard cars, trucks, SUVs,
          and vans, and <strong>$65</strong> for motorcycles, ATVs, and boats, per Copart&apos;s
          published fee schedule. It applies to every purchase and cannot be waived. It is separate
          from the $15 environmental fee, and separate from storage: payment is due within 3
          business days including sale day, a $50 late fee applies after that, and storage starts
          accruing once the free window closes. Fees change; verify the current amount on
          Copart&apos;s official member-fees page before you bid.
        </p>

        <h2 className={styles.h2}>When the gate pass issues</h2>
        <p className={styles.p}>
          The gate pass does not appear when you pay. It appears when your payment <em>clears</em>.
          That distinction costs first-time buyers days of storage fees.
        </p>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Payment method</th>
              <th>Typical clearance</th>
              <th>Gate pass timing</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Wire transfer</td>
              <td>Same or next business day</td>
              <td>Morning after clearance</td>
            </tr>
            <tr>
              <td>CashierPay</td>
              <td>1-2 business days</td>
              <td>Day 2-3</td>
            </tr>
            <tr>
              <td>Cashier&apos;s check</td>
              <td>2-3 business days</td>
              <td>Day 3-4</td>
            </tr>
            <tr>
              <td>Personal check</td>
              <td>Not accepted for first-time buyers</td>
              <td>N/A</td>
            </tr>
          </tbody>
        </table>
        <p className={styles.p}>
          Pay by wire same day if you can. Every hour delay shortens the free-window runway.
        </p>

        <h2 className={styles.h2}>What the carrier needs at the gate</h2>
        <p className={styles.p}>
          Five items, all must match:
        </p>
        <ol className={styles.list}>
          <li className={styles.listItem}><strong>Buyer or member number</strong> — your Copart account ID.</li>
          <li className={styles.listItem}><strong>Lot number</strong> — the specific auction lot.</li>
          <li className={styles.listItem}><strong>Cleared payment confirmation</strong> — pulled up by the yard&apos;s system.</li>
          <li className={styles.listItem}><strong>Gate pass PIN</strong> — digital, visible in the Copart buyer portal once generated.</li>
          <li className={styles.listItem}><strong>Driver name matching the dispatch record</strong> — if a different driver shows up, the yard sends them back.</li>
        </ol>

        <h2 className={styles.h2}>Transporter App requirements</h2>
        <p className={styles.p}>
          Many Copart yards require the carrier to check in via the Copart Transporter App.
          Drivers without an app account wait longer in line or, at some yards during peak hours,
          get turned away entirely. This is a real issue for out-of-network carriers; it is one
          reason Y7 cross-checks app status before dispatch.
        </p>

        <h2 className={styles.h2}>Common failure modes</h2>
        <h3 className={styles.h3}>1. Unpaid auction fees on the account</h3>
        <p className={styles.p}>
          Any outstanding balance (relist fees, prior late fees, buyer-number maintenance fees)
          can block gate pass generation on the new lot. Fix: log into the buyer portal before
          dispatch and confirm no holds. Pay anything outstanding.
        </p>

        <h3 className={styles.h3}>2. Expired gate pass PIN</h3>
        <p className={styles.p}>
          Some yards time-limit the PIN. If the carrier does not arrive within the validity
          window, the pass may need regeneration. Fix: coordinate pickup timing closely with
          gate-pass issuance.
        </p>

        <h3 className={styles.h3}>3. Driver-name mismatch</h3>
        <p className={styles.p}>
          The original dispatch named Driver A. Driver A got stuck on another load; the carrier
          sent Driver B. Driver B arrives, yard sees the mismatch, sends them back. Fix: the
          broker updates the dispatch record before the driver leaves for the yard.
        </p>

        <h3 className={styles.h3}>4. Yard appointment required, none booked</h3>
        <p className={styles.p}>
          High-volume urban yards (Copart 202 LA, 203 Van Nuys, 204 Long Beach, and similar
          metros) require scheduled appointments during peak hours. Walk-in pickups wait or get
          rescheduled. Fix: broker books the appointment when dispatching the carrier.
        </p>

        <h3 className={styles.h3}>5. Vehicle condition different from listing</h3>
        <p className={styles.p}>
          &quot;Runs and drives&quot; → dead battery, no keys. The driver came with a regular
          trailer; now a winch is needed. Either the driver finds another solution on the lot or
          the pickup is rescheduled — another storage day. Fix: disclose accurately on the quote.
        </p>

        <h2 className={styles.h2}>Yard hours — the 4:30 PM rule</h2>
        <p className={styles.p}>
          A yard that &quot;opens&quot; until 5:00 PM typically <em>stops loading</em> at 4:30 PM.
          A driver arriving at 4:35 gets turned away for the day. That is another 24 hours on the
          storage clock. Dispatch timing for afternoon arrivals matters — and so does local
          traffic between the driver&apos;s prior drop and the Copart yard.
        </p>
        <p className={styles.p}>
          Some yards have shorter hours on Saturdays and are closed Sundays. Friday wins with a
          Saturday-intended pickup are particularly exposed to this.
        </p>

        <h2 className={styles.h2}>When carriers refuse certain yards</h2>
        <p className={styles.p}>
          Worth knowing: some carriers will not accept dispatches to specific Copart yards at all
          — usually because of congestion, distance from their usual route, or a bad experience
          with yard staff. &quot;Yard refused&quot; is a real load-board status. A broker with
          a deeper carrier pool can reach past these refusals; a broker with a narrow in-network
          pool cannot.
        </p>

        <h2 className={styles.h2}>If the gate turns the carrier away</h2>
        <p className={styles.p}>
          The carrier leaves. The storage clock keeps running. The broker identifies the root
          cause (unpaid fees, expired PIN, driver mismatch, appointment, condition issue) and
          rebooks — same carrier if still available, different carrier if not. Expect at least
          one lost day in most turn-away scenarios.
        </p>

        <h2 className={styles.h2}>Related</h2>
        <ul className={styles.list}>
          <li className={styles.listItem}><Link to="/copart-shipping" className={styles.link}>Copart shipping main page</Link></li>
          <li className={styles.listItem}><Link to="/copart-storage-fees" className={styles.link}>Copart storage fees guide</Link></li>
          <li className={styles.listItem}><Link to="/copart-international-shipping" className={styles.link}>Copart international shipping</Link></li>
          <li className={styles.listItem}><Link to="/how-to-ship-a-car-bought-at-auction" className={styles.link}>How to ship a car bought at auction</Link></li>
        </ul>
      </div>
    </div>
  );
}
