import { Link } from 'react-router-dom';
import PageMeta from '../../../components/PageMeta';
import BreadcrumbSchema from '../../../components/BreadcrumbSchema';
import { colors, fonts } from '../../../theme';

const h2Style = { fontFamily: fonts.serif, fontSize: '22px', fontWeight: 700, color: colors.text, marginBottom: '16px', marginTop: '48px' };
const h3Style = { fontFamily: fonts.serif, fontSize: '17px', fontWeight: 700, color: colors.text, marginBottom: '10px', marginTop: '28px' };
const pStyle = { fontFamily: fonts.sans, fontSize: '15px', color: colors.textMuted, lineHeight: 1.7, marginBottom: '16px' };
const liStyle = { fontFamily: fonts.sans, fontSize: '15px', color: colors.textMuted, lineHeight: 1.7, marginBottom: '8px' };
const linkStyle = { color: colors.accent, textDecoration: 'none', fontWeight: 600, borderBottom: `1px solid ${colors.accent}` };

const tableStyle = { width: '100%', borderCollapse: 'collapse', fontFamily: fonts.sans, fontSize: '14px', margin: '12px 0 24px' };
const thStyle = { textAlign: 'left', padding: '10px 12px', borderBottom: `2px solid ${colors.border}`, background: colors.bgMuted, fontWeight: 700, color: colors.text };
const tdStyle = { padding: '10px 12px', borderBottom: `1px solid ${colors.border}`, color: colors.textMuted };

export default function CopartGatePassGuide() {
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '60px 24px 80px' }}>
      <PageMeta
        title="Copart Gate Pass Guide — How It Works, Common Failures, Yard Cutoffs"
        description="Technical guide to Copart gate passes. Generation timing, payment clearance, Transporter App requirements, common failure modes, and yard cutoff times that control pickup."
        path="/copart-gate-pass-guide"
      />
      <BreadcrumbSchema items={[
        { name: 'Home', url: '/' },
        { name: 'Copart Shipping', url: '/copart-shipping' },
        { name: 'Gate Pass Guide', url: '/copart-gate-pass-guide' },
      ]} />

      <nav aria-label="Breadcrumb" style={{ fontFamily: fonts.sans, fontSize: '13px', color: colors.textMuted, marginBottom: '24px' }}>
        <Link to="/" style={{ color: colors.textMuted }}>Home</Link>
        <span style={{ margin: '0 6px' }}>/</span>
        <Link to="/copart-shipping" style={{ color: colors.textMuted }}>Copart Shipping</Link>
        <span style={{ margin: '0 6px' }}>/</span>
        <span style={{ color: colors.text }}>Gate Pass Guide</span>
      </nav>

      <h1 style={{ fontFamily: fonts.serif, fontSize: 'clamp(28px, 4vw, 40px)', fontWeight: 700, color: colors.text, marginBottom: '16px', lineHeight: 1.2 }}>
        The Copart Gate Pass: How It Works, Why It Fails, and Why Yard Cutoffs Control Pickup
      </h1>

      <p style={{ ...pStyle, fontSize: '16px', marginBottom: '36px', color: colors.text }}>
        This is the technical process documentation. If a carrier gets turned away at a Copart
        yard, one of the items below is almost always the reason. Understanding the mechanics
        saves dispatches, saves storage days, and saves the &quot;why is my car still sitting at
        the yard&quot; phone call.
      </p>

      <h2 style={h2Style}>What a Copart gate pass actually is</h2>
      <p style={pStyle}>
        A gate pass is a digital release authorization generated by Copart once your payment has
        cleared and the account is in good standing. It ties together: buyer number, lot number,
        vehicle identifier, and a gate pass PIN. Without it, yard security turns carriers back —
        no exceptions, no arguing, no supervisor override.
      </p>

      <h2 style={h2Style}>How much is the Copart gate fee in 2026?</h2>
      <p style={pStyle}>
        The Copart gate fee is <strong>$95 per vehicle</strong> for standard cars, trucks, SUVs,
        and vans, and <strong>$65</strong> for motorcycles, ATVs, and boats, per Copart&apos;s
        published fee schedule. It applies to every purchase and cannot be waived. It is separate
        from the $15 environmental fee, and separate from storage: payment is due within 3
        business days including sale day, a $50 late fee applies after that, and storage starts
        accruing once the free window closes. Fees change; verify the current amount on
        Copart&apos;s official member-fees page before you bid.
      </p>

      <h2 style={h2Style}>When the gate pass issues</h2>
      <p style={pStyle}>
        The gate pass does not appear when you pay. It appears when your payment <em>clears</em>.
        That distinction costs first-time buyers days of storage fees.
      </p>
      <table style={tableStyle}>
        <thead>
          <tr>
            <th style={thStyle}>Payment method</th>
            <th style={thStyle}>Typical clearance</th>
            <th style={thStyle}>Gate pass timing</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style={tdStyle}>Wire transfer</td>
            <td style={tdStyle}>Same or next business day</td>
            <td style={tdStyle}>Morning after clearance</td>
          </tr>
          <tr>
            <td style={tdStyle}>CashierPay</td>
            <td style={tdStyle}>1-2 business days</td>
            <td style={tdStyle}>Day 2-3</td>
          </tr>
          <tr>
            <td style={tdStyle}>Cashier&apos;s check</td>
            <td style={tdStyle}>2-3 business days</td>
            <td style={tdStyle}>Day 3-4</td>
          </tr>
          <tr>
            <td style={tdStyle}>Personal check</td>
            <td style={tdStyle}>Not accepted for first-time buyers</td>
            <td style={tdStyle}>N/A</td>
          </tr>
        </tbody>
      </table>
      <p style={pStyle}>
        Pay by wire same day if you can. Every hour delay shortens the free-window runway.
      </p>

      <h2 style={h2Style}>What the carrier needs at the gate</h2>
      <p style={pStyle}>
        Five items, all must match:
      </p>
      <ol style={pStyle}>
        <li style={liStyle}><strong>Buyer or member number</strong> — your Copart account ID.</li>
        <li style={liStyle}><strong>Lot number</strong> — the specific auction lot.</li>
        <li style={liStyle}><strong>Cleared payment confirmation</strong> — pulled up by the yard&apos;s system.</li>
        <li style={liStyle}><strong>Gate pass PIN</strong> — digital, visible in the Copart buyer portal once generated.</li>
        <li style={liStyle}><strong>Driver name matching the dispatch record</strong> — if a different driver shows up, the yard sends them back.</li>
      </ol>

      <h2 style={h2Style}>Transporter App requirements</h2>
      <p style={pStyle}>
        Many Copart yards require the carrier to check in via the Copart Transporter App.
        Drivers without an app account wait longer in line or, at some yards during peak hours,
        get turned away entirely. This is a real issue for out-of-network carriers; it is one
        reason Y7 cross-checks app status before dispatch.
      </p>

      <h2 style={h2Style}>Common failure modes</h2>
      <h3 style={h3Style}>1. Unpaid auction fees on the account</h3>
      <p style={pStyle}>
        Any outstanding balance (relist fees, prior late fees, buyer-number maintenance fees)
        can block gate pass generation on the new lot. Fix: log into the buyer portal before
        dispatch and confirm no holds. Pay anything outstanding.
      </p>

      <h3 style={h3Style}>2. Expired gate pass PIN</h3>
      <p style={pStyle}>
        Some yards time-limit the PIN. If the carrier does not arrive within the validity
        window, the pass may need regeneration. Fix: coordinate pickup timing closely with
        gate-pass issuance.
      </p>

      <h3 style={h3Style}>3. Driver-name mismatch</h3>
      <p style={pStyle}>
        The original dispatch named Driver A. Driver A got stuck on another load; the carrier
        sent Driver B. Driver B arrives, yard sees the mismatch, sends them back. Fix: the
        broker updates the dispatch record before the driver leaves for the yard.
      </p>

      <h3 style={h3Style}>4. Yard appointment required, none booked</h3>
      <p style={pStyle}>
        High-volume urban yards (Copart 202 LA, 203 Van Nuys, 204 Long Beach, and similar
        metros) require scheduled appointments during peak hours. Walk-in pickups wait or get
        rescheduled. Fix: broker books the appointment when dispatching the carrier.
      </p>

      <h3 style={h3Style}>5. Vehicle condition different from listing</h3>
      <p style={pStyle}>
        &quot;Runs and drives&quot; → dead battery, no keys. The driver came with a regular
        trailer; now a winch is needed. Either the driver finds another solution on the lot or
        the pickup is rescheduled — another storage day. Fix: disclose accurately on the quote.
      </p>

      <h2 style={h2Style}>Yard hours — the 4:30 PM rule</h2>
      <p style={pStyle}>
        A yard that &quot;opens&quot; until 5:00 PM typically <em>stops loading</em> at 4:30 PM.
        A driver arriving at 4:35 gets turned away for the day. That is another 24 hours on the
        storage clock. Dispatch timing for afternoon arrivals matters — and so does local
        traffic between the driver&apos;s prior drop and the Copart yard.
      </p>
      <p style={pStyle}>
        Some yards have shorter hours on Saturdays and are closed Sundays. Friday wins with a
        Saturday-intended pickup are particularly exposed to this.
      </p>

      <h2 style={h2Style}>When carriers refuse certain yards</h2>
      <p style={pStyle}>
        Worth knowing: some carriers will not accept dispatches to specific Copart yards at all
        — usually because of congestion, distance from their usual route, or a bad experience
        with yard staff. &quot;Yard refused&quot; is a real load-board status. A broker with
        a deeper carrier pool can reach past these refusals; a broker with a narrow in-network
        pool cannot.
      </p>

      <h2 style={h2Style}>If the gate turns the carrier away</h2>
      <p style={pStyle}>
        The carrier leaves. The storage clock keeps running. The broker identifies the root
        cause (unpaid fees, expired PIN, driver mismatch, appointment, condition issue) and
        rebooks — same carrier if still available, different carrier if not. Expect at least
        one lost day in most turn-away scenarios.
      </p>

      <h2 style={h2Style}>Related</h2>
      <ul style={pStyle}>
        <li style={liStyle}><Link to="/copart-shipping" style={linkStyle}>Copart shipping main page</Link></li>
        <li style={liStyle}><Link to="/copart-storage-fees" style={linkStyle}>Copart storage fees guide</Link></li>
        <li style={liStyle}><Link to="/copart-international-shipping" style={linkStyle}>Copart international shipping</Link></li>
        <li style={liStyle}><Link to="/how-to-ship-a-car-bought-at-auction" style={linkStyle}>How to ship a car bought at auction</Link></li>
      </ul>
    </div>
  );
}
