// W2-T12: derive src/data/dispatchRates.js from the append-only source set
// src/data/rates/*.csv (real Central Dispatch carrier rates Sergii paid).
//
// APPEND-ONLY CONTRACT: drop any new export (e.g. the May–June 2026 V1
// calibration loads, pending export from the CD shipper dashboard) into
// src/data/rates/ and re-run `node scripts/derive-rates.mjs` — zero code
// changes required. Rows are deduplicated ACROSS FILES ONLY by the
// (pickup_zip, dest_zip, miles, price_usd) tuple (CD exports carry no load
// id): repeat orders inside one export are legitimate loads and are kept;
// the tuple guard only prevents the same load re-entering via an
// overlapping second export.
// Only vehicle_class === 'standard' feeds the band model; other classes
// (van / premium / expedited) are excluded from the model but kept in the
// sources for provenance.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const SRC_DIR = path.join(ROOT, 'src/data/rates');
const OUT = path.join(ROOT, 'src/data/dispatchRates.js');

const BANDS = [
  [0, 50], [51, 150], [151, 300], [301, 500], [501, 800], [801, 1200], [1201, Infinity],
];

function parseCsv(text) {
  const [head, ...lines] = text.replace(/^\uFEFF/, '').trim().split(/\r?\n/);
  const cols = head.split(',');
  return lines.map(l => {
    const cells = l.split(',');
    return Object.fromEntries(cols.map((c, i) => [c.trim(), (cells[i] || '').trim()]));
  });
}

const files = fs.readdirSync(SRC_DIR).filter(f => f.endsWith('.csv')).sort();
if (!files.length) throw new Error('no source csv files in src/data/rates');

const seen = new Set();
let all = [], perFile = {};
for (const f of files) {
  const rows = parseCsv(fs.readFileSync(path.join(SRC_DIR, f), 'utf8'));
  const fileKeys = new Set();
  let kept = 0, dup = 0;
  for (const r of rows) {
    const key = [r.pickup_zip, r.dest_zip, r.miles, r.price_usd].join('|');
    if (seen.has(key)) { dup++; continue; } // cross-file duplicate only
    fileKeys.add(key);
    all.push(r);
    kept++;
  }
  for (const k of fileKeys) seen.add(k);
  perFile[f] = { rows: rows.length, kept, crossFileDup: dup };
}

const std = all.filter(r => r.vehicle_class === 'standard'
  && Number(r.miles) >= 0 && r.miles !== '' && Number(r.price_usd) > 0); // miles=0 = real same-yard moves
const excluded = all.length - std.length;

const q = (v, p) => {
  const s = [...v].sort((a, b) => a - b);
  const k = (s.length - 1) * p, f = Math.floor(k), c = Math.min(f + 1, s.length - 1);
  return Math.round(s[f] + (s[c] - s[f]) * (k - f));
};

const bands = BANDS.map(([lo, hi]) => {
  const prices = std.filter(r => Number(r.miles) >= lo && Number(r.miles) <= hi)
    .map(r => Number(r.price_usd));
  return {
    minMiles: lo,
    maxMiles: hi === Infinity ? null : hi,
    n: prices.length,
    median: q(prices, 0.5),
    p25: q(prices, 0.25),
    p75: q(prices, 0.75),
  };
});

const body = `// GENERATED by scripts/derive-rates.mjs — do not edit by hand.
// Regenerate: node scripts/derive-rates.mjs   (reads src/data/rates/*.csv, append-only)
//
// Source set: ${files.join(', ')}
// Rows: ${all.length} after cross-file dedup (${Object.entries(perFile).map(([f, s]) => `${f}: ${s.rows} rows, ${s.dup} dup`).join('; ')})
// Model basis: vehicle_class=standard only (${std.length} rows; ${excluded} rows excluded: van/premium/expedited kept in sources for provenance).
// Figures are CARRIER rates actually paid (open transport). Y7's flat dispatch
// fee is quoted per customer and never derived from this table.
//
// V1 PRIOR (PHASE5A magnet formula, calibrated to ~75 CD loads May-Jun 2026;
// raw rows pending export from the CD dashboard - see append-only contract):
//   carrierMid(miles) = max(150, 115 + 10 * miles^0.55)
// Divergence vs this table (band median minus formula at band-median miles):
//   0-50: -63 | 51-150: -34 | 151-300: -63 | 301-500: -34 | 501-800: +42
//   | 801-1200: +3 | 1200+: +228  (formula leans high short-haul, low 1200+)
//
// UI LAW: the 1200+ band renders p25-p75 ONLY (n=${bands[bands.length - 1].n} - median unstable);
// all figures are hedged as "typical range from recent dispatches", never a
// guaranteed price (DESIGN.md paragraph 8 honesty laws).

export const DISPATCH_RATE_BANDS = ${JSON.stringify(bands, null, 2)};

export function lookupBand(miles) {
  return DISPATCH_RATE_BANDS.find(
    (b) => miles >= b.minMiles && (b.maxMiles === null || miles <= b.maxMiles)
  ) || null;
}
`;
fs.writeFileSync(OUT, body);
console.log('wrote', OUT);
console.log(JSON.stringify({ files: perFile, total: all.length, standard: std.length, bands }, null, 1));
