export const colors = {
  bg: '#F7F5F0',
  bgCard: '#FFFFFF',
  bgMuted: '#EFECE6',
  bgInput: '#F7F5F0',
  text: '#2C2C2A',
  textMuted: '#888780',
  textHint: '#999',
  accent: '#993C1D',
  accentHover: '#7A3017',
  dark: '#2C2C2A',
  success: '#0F6E56',
  successBg: '#E1F5EE',
  border: '#e5e0d8',
  borderInput: '#ddd',
};

export const fonts = {
  serif: "Georgia, 'Times New Roman', serif",
  sans: "system-ui, -apple-system, sans-serif",
  mono: "'JetBrains Mono', 'Courier New', monospace",
};

export const button = {
  primary: {
    background: colors.dark,
    color: colors.bg,
    padding: '10px 24px',
    borderRadius: '20px',
    fontSize: '12px',
    border: 'none',
    cursor: 'pointer',
    fontFamily: fonts.sans,
    fontWeight: 600,
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  },
  secondary: {
    background: 'transparent',
    color: colors.dark,
    padding: '10px 24px',
    borderRadius: '20px',
    border: '0.5px solid #ccc',
    fontSize: '12px',
    cursor: 'pointer',
    fontFamily: fonts.sans,
    fontWeight: 600,
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  },
  accent: {
    background: colors.accent,
    color: '#fff',
    padding: '10px 24px',
    borderRadius: '20px',
    fontSize: '12px',
    border: 'none',
    cursor: 'pointer',
    fontFamily: fonts.sans,
    fontWeight: 600,
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  },
};
